language: node_js
node_js:
  - "6"
  - "5"
  - "4"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
services:
  - mongodb
script:
  - npm run build
after_success:
  - npm test
env:
  - TRAVIS=travis CXX=g++-4.8
